name: rh-csharp-ubuntu

on:
  workflow_dispatch:
    inputs:
      workingDirectory:
        description: 'Working directory'     
        required: true
        default: 'src'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.event.inputs.workingDirectory }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
