name: test

on:
  workflow_dispatch:

jobs:
  experimenting:

    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo Hello World
      - name: Echo (grouped)
        run: |
          echo "::group::Hello group"
          echo "Hello GitHub"
          echo "Hello World"
          echo "Hello Universe"
          echo "::endgroup::"
      - name: Debug
        run: echo "::debug ::I am a debug message"
      - name: Warning
        run: echo "::warning ::I am a warning message"
      - name: Error
        run: echo "::error ::I am an error message"
