name: test

on:
  workflow_dispatch:

jobs:
  experimenting:

    runs-on: ubuntu-latest

    steps:
      - name: Echo1
        run: echo Hello World
      - name: Echo2
        run: echo "::set-output name=action_fruit::strawberry"
